### ISSUE TITLE
Rename this repo and other suggestions

### ISSUE THREAD

**Issue by gnatih** [DatameetAMD/openamdcontributingdata#1]
Please rename this repo to a less confusing (and short) name. Also this repo needs to be the documentation/wiki micro-site for openahmedabad.org, so may be just call it ```docs.openahmedabad.org```. Ideally it should hosted at [docs.openahmedabad.org](https://docs.openahmedabad.org). 

It will contain concise articles on working with data, software tools, how-to etc.

**Comment by shravan91** [comment]
Renamed this repo to **datacontributionOpenAMD**

cc @jimishio

**Comment by gnatih** [comment]
I think I said short as well. @shravan91
